/**
 * Start Trigger.dev dev with NEXTFLOW_PROJECT_ROOT set so local PGlite
 * resolves to ./data/pglite instead of .trigger/tmp/build-*.
 */
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { spawn } from "node:child_process";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const projectRoot = dirname(dirname(fileURLToPath(import.meta.url)));
const triggerDir = join(projectRoot, ".trigger");
const generatedEnvPath = join(triggerDir, "dev-env.generated");
const localEnvPath = join(projectRoot, ".env.local");

mkdirSync(triggerDir, { recursive: true });

const localEnv = existsSync(localEnvPath)
  ? readFileSync(localEnvPath, "utf8")
  : "";

writeFileSync(
  generatedEnvPath,
  [
    localEnv.trimEnd(),
    `# Generated by scripts/trigger-dev.mjs — do not commit`,
    `NEXTFLOW_PROJECT_ROOT=${projectRoot.replace(/\\/g, "/")}`,
    `INIT_CWD=${projectRoot.replace(/\\/g, "/")}`,
    "",
  ]
    .filter(Boolean)
    .join("\n"),
  "utf8",
);

const args = [
  "trigger",
  "dev",
  "--skip-mcp-install",
  "--skip-rules-install",
  "--env-file",
  generatedEnvPath,
];

const child = spawn("npx", args, {
  cwd: projectRoot,
  env: {
    ...process.env,
    INIT_CWD: projectRoot,
    NEXTFLOW_PROJECT_ROOT: projectRoot,
  },
  stdio: "inherit",
  shell: process.platform === "win32",
});

child.on("exit", (code, signal) => {
  if (signal) {
    process.kill(process.pid, signal);
    return;
  }

  process.exit(code ?? 0);
});

child.on("error", (error) => {
  console.error(error);
  process.exit(1);
});
